export const type = {
    EMIT_ERROR: 'EMIT_ERROR',
    ADD_SPINNER: 'ADD_SPINNER',
    REMOVE_SPINNER: 'REMOVE_SPINNER',
    SET_LIST_VIEW_MODE: 'SET_LIST_VIEW_MODE',
    SET_LIST_SORT_ORDER: 'SET_LIST_SORT_ORDER',
    SET_LIST_FILTER_TITLE: 'SET_LIST_FILTER_TITLE',
    SET_LIST_FILTER_STAR: 'SET_LIST_FILTER_STAR',
}
