export const type = {
    // Syn
    FILL_FILMS: 'FILL_FILMS',
    UPDATE_FILM: 'UPDATE_FILM',
    CREATE_FILM: 'CREATE_FILM',
    REMOVE_FILM: 'REMOVE_FILM',
    // Asyn
    FETCH_FILMS_ASYNC: 'FETCH_FILMS_ASYNC',
    UPDATE_FILM_ASYNC: 'UPDATE_FILM_ASYNC',
    CREATE_FILM_ASYNC: 'CREATE_FILM_ASYNC',
    REMOVE_FILM_ASYNC: 'REMOVE_FILM_ASYNC',
}
