export const type = {
    // Syn
    FILL_FILMS: 'FILL_FILMS',
    UPDATE_FILM: 'UPDATE_FILM',
    CREATE_FILM: 'CREATE_FILM',
    REMOVE_FILM: 'REMOVE_FILM',
    SET_EDIT_MODE_FILM: 'SET_EDIT_MODE_FILM',
    SET_VIEW_MODE_FILM: 'SET_VIEW_MODE_FILM',
    SET_NEW_TITLE_FILM: 'SET_NEW_TITLE_FILM',
    SET_NEW_FORMAT_FILM: 'SET_NEW_FORMAT_FILM',
    SET_NEW_STARS_FILM: 'SET_NEW_STARS_FILM',
    SET_NEW_YEAR_FILM: 'SET_NEW_YEAR_FILM',
    // Async
    FETCH_FILMS_ASYNC: 'FETCH_FILMS_ASYNC',
    UPDATE_FILM_ASYNC: 'UPDATE_FILM_ASYNC',
    CREATE_FILM_ASYNC: 'CREATE_FILM_ASYNC',
    REMOVE_FILM_ASYNC: 'REMOVE_FILM_ASYNC',
}
